server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rserver?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: rache
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rache.racheserver.mapper

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.mybatis: DEBUG

storage:
  dir: "D:/server/rache-server"

music:
  audio-dir: ${storage.dir}/music/audio
  cover-dir: ${storage.dir}/music/cover
